version: "3.9"

services:
  app:
    build: .
    image: anonym-messages
    command: gunicorn main:app --workers 1 --port 8000  --worker-class uvicorn.workers.UvicornWorker
    depends:
      - db
    restart: always

  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  db_data:
