"""Added a sended_date column

Revision ID: 19a7655ab525
Revises: 9d86819199dc
Create Date: 2025-07-07 11:18:37.974836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from source.database_service.database_config import Base


# revision identifiers, used by Alembic.
revision: str = '19a7655ab525'
down_revision: Union[str, None] = '9d86819199dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sended_date', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sended_date')
    # ### end Alembic commands ###
