"""Create_all_tables

Revision ID: 9d86819199dc
Revises: 
Create Date: 2025-03-01 15:56:26.306091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from source.database_service.database_config import Base


# revision identifiers, used by Alembic.
revision: str = '9d86819199dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('refresh_token_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_uid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_uid', sa.String(), nullable=True),
    sa.Column('to_user_uid', sa.String(), nullable=True),
    sa.Column('reply_to_message', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_uid'], ['users.user_uid'], ),
    sa.ForeignKeyConstraint(['to_user_uid'], ['users.user_uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('users')
    # ### end Alembic commands ###
