"""Create Users table

Revision ID: f341985c38df
Revises: 
Create Date: 2025-01-14 18:38:40.608980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from source.database_service.database_config import Base


# revision identifiers, used by Alembic.
revision: str = 'f341985c38df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
