stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "$DOT_TEST_ENV_file" > ci_cd/tests/.env
    - echo "$DOT_PROD_ENV_file" > ci_cd/deploy/.env
    - "docker build  . -t anonym-messages"


test-job:
  stage: test
  script:
    - "docker-compose -f ci-cd/tests/docker-compose.yaml up -d"
  after_script:
    - "docker-compose -f ci-cd/tests/docker-compose.yaml down"


deploy-job:
  stage: deploy
  script:
    - "docker-compose -f ci-cd/deploy/docker-compose.yaml"
