variables:
    DOCKER_HOST: unix:///var/run/docker.sock

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - "docker compose -f ci_cd/deploy/docker-compose.yaml build"

test-job:
  stage: test
  before_script:
    - echo $DOT_TEST_ENV_FILE
    - echo "$DOT_TEST_ENV_FILE" > ci_cd/tests/.env
    - source ci_cd/tests/.env
  script: |
    docker-compose -f ci_cd/tests/docker-compose.yaml up \
    --exit-code-from app \
    --abort-on-container-exit
  after_script:
    - "docker compose -f ci_cd/test/docker-compose.yaml down"
    
  artifacts:
    paths:
      - coverage/coverage.json
    expire_in: 1 week

check-coverage-job:
  stage: test
  dependencies:
    - test-job
  script:
    - |
      docker run \
        --rm \
        -v /coverage:/coverage \
        anonym-messages coverage report \
          --fail-under=80 \
          --data-file=coverage/coverage.json
  allow_failure: true

deploy-job:
  stage: deploy
  before_script:
    - echo "$DOT_PROD_ENV_FILE" > ci_cd/deploy/.env
    - source ci_cd/deploy/.env
  script:
    - "docker-compose -f ci_cd/deploy/docker-compose.yaml up -d"
