stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - "docker build  . -t anonym-messages"


test-job:
  stage: test
  before_script:
    - echo $DOT_TEST_ENV_FILE
    - echo "$DOT_TEST_ENV_FILE" | tail -n +2 > ci_cd/tests/.env
    - source ci_cd/tests/.env
  script: |
    docker-compose -f ci_cd/tests/docker-compose.yaml up \
    --exit-code-from app \
    --remove-orphans \
    --abort-on-container-exit
  artifacts:
    paths:
      - coverage/coverage.json
    expire_in: 1 week


check-coverage-job:
  stage: test
  dependencies:
    - test-job
  script:
    - |
      docker run \
        --rm \
        -v /coverage:/coverage \
        anonym-messages coverage report \
          --fail-under=80 \
          --data-file=coverage/coverage.json
  allow_failure: true


deploy-job:
  stage: deploy
  before_script:
    - echo "$DOT_PROD_ENV_FILE" | tail -n +2 > ci_cd/deploy/.env
    - source ci_cd/deploy/.env
  script:
    - "docker-compose -f ci_cd/deploy/docker-compose.yaml up -d"
