stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - "docker build  . -t anonym-messages"


test-job:
  stage: test
  before_script:
    - echo "$DOT_TEST_ENV_FILE" | tail -n +2 > ci_cd/tests/.env
  script:
    - "docker-compose -f ci_cd/tests/docker-compose.yaml up -d"
  after_script:
    - "docker-compose -f ci_cd/tests/docker-compose.yaml down"


check-coverage-job:
  stage: test
  dependencies:
    - test-job
  before_script:
    - echo "$DOT_PROD_ENV_FILE" | tail -n +2 > ci_cd/deploy/.env
  script:
    - "docker run --rm -v /coverage:/coverage anonym-messages python ci_cd/test/check_coverage.py coverage/coverage.json 80"


deploy-job:
  stage: deploy
  before_script:
    - echo "$DOT_TEST_ENV_FILE" > ci_cd/tests/.env
    - echo "$DOT_PROD_ENV_FILE" > ci_cd/deploy/.env
  script:
    - "docker-compose -f ci_cd/deploy/docker-compose.yaml"
