version: "3.9"

services:
  app:
    build: .
    image: anonym-messages
        command: |
          alembic upgrade head && \
          gunicorn main:app \
            --workers 1 \
            --port 8000 \
            --worker-class uvicorn.workers.UvicornWorker
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always

volumes:
  db_data:
