version: "3.9"

services:
  app:
    build: .
    image: anonym-messages
    command: |
      alembic upgrade head && \
      gunicorn main:app \
        --workers 1 \
        --port 8000 \
        --worker-class uvicorn.workers.UvicornWorker
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

volumes:
  db_data:
