services:
  db:
    image: postgres:16
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 5
    restart: unless-stopped
    networks:
      - main_network
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: ../../
    image: anonym-messages
    command: ci_cd/deploy/command.sh
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - main_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - app
    networks:
      - main_network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - "./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - main_network
    depends_on:
      - nginx

  node_exporter:
    image: prom/node-exporter
    networks:
      - main_network

networks:
  main_network:
    driver: bridge

volumes:
  db_data:
