global:
  scrape_interval: 10s
  scrape_timeout: 5s
  external_labels:
    monitor: "app-monitor"

scrape_configs:
  - job_name: "node_exporter"
    metrics_path: /metrics
    scheme: http

    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "app-nginx"
    metrics_path: /metrics
    scheme: http

    static_configs:
      - targets: ["app:8000"]

  # опционально — заголовки для basic-auth, custom-headers и т.п.
  # basic_auth:
  #   username: prometheus
  #   password: secret
